### ISSUE TITLE
How can I find Train Code?

### ISSUE THREAD

**Issue by accer-iou** [neerajwagh/eeg-gcnn#1]
Impressive Work! Could you please provide train code?

**Comment by neerajwagh** [comment]
Hi @zhaoyanxi , thanks for your interest! I'm currently working on cleaning up the training code for public release. I'll try to release it in a week or two. I apologize for the delay, the original repo was only meant to enable others to reproduce the results with trained models.

If you're unable to wait, you can adapt the training code from this colab example - https://colab.research.google.com/drive/1I8a0DfQ3fI7Njc62__mVXUlcAleUclnb?usp=sharing and plug in the EEG-GCNN model definition files for the forward pass. There are more examples of GNN training at https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html.

**Comment by neerajwagh** [comment]
https://github.com/neerajwagh/eeg-gcnn/blob/master/training_pipeline.py
