### ISSUE TITLE
question about spatial adjacency matrix

### ISSUE THREAD

**Issue by jukebox333** [neerajwagh/eeg-gcnn#10]
Hi, neerajwagh！
The EEG-GCNN is a great job, thank you for sharing the related code!
May I ask why you use geodesic distance to build the spatial adjacency matrix, is it to extract spatial features?
If so, since the position of the electrodes on the EEG cap is fixed, is the spatial adjacency matrix the same for each sample?

**Comment by neerajwagh** [comment]
Yes, that is correct - the adjacency matrix is fixed for each sample and leads to a fairly simplistic/naive model of the brain.

If you have localizer data from the EEG caps or other modalities like MRI for the same subject, you can start to build more realistic spatial connectivity features.
