### ISSUE TITLE
Work with eeg-sliding window GCNN

### ISSUE THREAD

**Issue by rajchordia14** [neerajwagh/eeg-gcnn#11]
Hello author,
The work you post is very good. We want to take this as a base for our model implementation. Currently, with this code, we are facing the following issues:
1) Dataset - we have tried to download the dataset from MP-Lemon as we r unable to register with the TUH EEG set. The problem while downloading the MP Lemon is we tried to download Raw data for 1 subject, and it showed 3 formats under that .edf format is not available. We request you, please add the dataset in .edf format in the repository.

Can you connect with me to better understand your model implementation?

**Comment by JOHNW02** [comment]
Hi there,

Thanks for reaching out. MPI Lemon releases their data in Brain Vision format. The API to process the format can be found in [MNE](https://mne.tools/stable/generated/mne.io.read_raw_brainvision.html). The code can process the .vhdr files.

John
