### ISSUE TITLE
about the TUAB dataset which labeled diseased.

### ISSUE THREAD

**Issue by daysofchasingdream** [neerajwagh/eeg-gcnn#12]
Hello author, your code has taught me a lot, but I have a question I would like to ask you.
In your thesis, you used 1385 subjects in TUAB and marked them as diseased, but I checked the content on the TUAB official website and found that these 1385 are theoretically normal EEG signals. Is there a mistake in my understanding, thank you for your guidance.
![image](https://user-images.githubusercontent.com/67813534/217236807-4ff386a0-2914-4b45-a62c-0a496a9b73a6.png)

**Comment by neerajwagh** [comment]
Thanks for your interest in the work.

The binary classification task we consider in the paper is between the normal healthy controls (MPI-LEMON-MBB) and visibly-normal diseased subjects (TUH-TUAB, hence the use of "normal" EEGs from the TUAB set). Differentiating these two classes of subjects is where clinicians are likely to need quantitative decision support since, in both cases, the EEGs look normal to the human eye. The results in the paper imply that there are subtle differences in these two classes that quantitative analysis can pick up even though the expert human eye cannot.

Hope that clarifies the use of "normal" EEGs from TUAB.

Neeraj

**Comment by daysofchasingdream** [comment]
Hello, thank you for your reply, I probably understand what you mean. That is, TUAB actually contains the data of patients. The so-called 'normal' here is just that the doctor did not distinguish it with the eyes, but in fact these people actually have epilepsy symptoms, right?
Thank you again.

**Comment by neerajwagh** [comment]
Yes! (Since TUH is a population dataset not specific to one disease, they could have any type of disorder, not just epilepsy. But yes, those TUAB-normal EEGs look normal on visual inspection.)

**Comment by daysofchasingdream** [comment]
> Yes! (Since TUH is a population dataset not specific to one disease, they could have any type of disorder, not just epilepsy. But yes, those TUAB-normal EEGs look normal on visual inspection.)

Thank you very much for your answer, I have benefited a lot from your answer.
I have one last small question. When you are labeling the "normal" class in TUAB as diseased, as shown in the picture below, are you labeling all the moments in 00008795_s001_t00.edf as diseased, or is this file actually much more than 1391s so much more, just 1391s of which happen to be seizure cases? (Since I can no longer download your original experimental version of the dataset, I would like to ask you for advice, thank you very much! I wish you all the best)
![image](https://user-images.githubusercontent.com/67813534/223127058-bdf00d97-f824-472e-8780-09c01e97d98a.png)

**Comment by daysofchasingdream** [comment]
I am now trying to use CNN, RNN, etc. to compare with this model of yours, so I would really like to know the principle of your dataset selection, thank you so much.

**Comment by neerajwagh** [comment]
TUAB normal/abnormal labels are not granular - only one label is given to the entire length of the recording. So we replicate/copy that recording-level label to all the 10-second EEG epochs derived from the full recording.

Looking forward to what you find in your comparison experiments.

Neeraj

**Comment by daysofchasingdream** [comment]
Thank you very much, I understand what you are doing in your code now. Thank you again for your answer, I really appreciate it.
