### ISSUE TITLE
File standard_1010.tsv.txt

### ISSUE THREAD

**Issue by Lokixin** [neerajwagh/eeg-gcnn#5]
Hi! 

I am trying to find the file "standard_1010.tsv.txt". You use it in the EEGGraphDataset class in the method get_sensor_distance. I am not able to find it in the repo, neither in the TUH dataset server or in your figshare. Is is possible to obtain this file? 

Thanks, awesome work!

**Comment by neerajwagh** [comment]
Hey @Lokixin - yes I forgot to add spec_coh_values.npy and standard_1010.tsv.txt to the version 2 of the figshare zip file. Version 1 still has these - https://figshare.com/articles/code/EEG-GCNN_Supporting_Resources_for_Reproducibility/13251452/1

You can take these from version 1, they're not changed. I'll update the figshare, thanks for pointing this out.

**Comment by neerajwagh** [comment]
https://figshare.com/articles/software/EEG-GCNN_Supporting_Resources_for_Reproducibility/13251452

**Comment by neerajwagh** [comment]
SOURCE: https://github.com/sappelhoff/eeg_positions/blob/main/data/Fpz-T8-Oz-T7/standard_1010_3D.tsv
