### ISSUE TITLE
Error during test run for Deep GCNN and Shallow GCNN

### ISSUE THREAD

**Issue by lucianodicristo22** [neerajwagh/eeg-gcnn#8]
Hi, 
When I try the test run with the pre processed data for the deep gcnn and the shallow gcnn i get the following error
![immagine](https://user-images.githubusercontent.com/71657674/194616591-a237e65a-dc04-4e52-9448-add9ebbead35.png)
and I'm having trouble figuring it out, do you have any suggestion?

Thank you for your work!

**Comment by JOHNW02** [comment]
Hi there,
Thanks for reaching out.
There is a version difference for pytorch-geometric library. We have updated the docker file. (https://github.com/neerajwagh/eeg-gcnn/blob/ec9f692a9a5ce53fea27711a3ffcec024581116f/Dockerfile#L92)

The heldout_test_run.py files are also updated. Please pull the latest version of the repo. 

Let us know if you run into any other issues. Thanks!
