### ISSUE TITLE
Processing my own eeg

### ISSUE THREAD

**Issue by lucianodicristo22** [neerajwagh/eeg-gcnn#9]
Hello, 
I'm noticing that the file to prepare other eeg and the eeg pipeline the oldest ones, and when I use them to produce my csv file it has some differences from the one on Figshare such as: the presence of the numeric label and the generic order of the columns.
Is that procedure sill valid to process my own eeg or there is an updated one?

Thank you for your work.

**Comment by JOHNW02** [comment]
Hi there,

Thanks for reaching out. **Although the .ipynb code is old, the CSV generated using it will still be valid for use in the other .py scripts.**
**Regarding numeric labels:** the code to generate numeric label in prepare_data_for_eeg-gcnn.ipynb is a convenient way to convert some text labels to numerical labels. For example, you might want to convert age into a binary classification problem of young vs. old. Then, when you prepare your data, you can easily get these labels with a condition statement.
**Regarding order of columns:** notice that the csv file is read and converted to a dataframe object. The columns are accessed by the column names so the order does not matter. An example of using columns can be seen here: https://github.com/neerajwagh/eeg-gcnn/blob/ec9f692a9a5ce53fea27711a3ffcec024581116f/code_psd_shallow_eeg_gcnn/heldout_test_run.py#L144.
Please let me know if you have any other questions.

John
